[nginx-ratelimit]
enabled  = true
port     = http,https
filter   = nginx-ratelimit
logpath  = /var/log/nginx/access.log
backend  = auto
maxretry = 30
findtime = 60
bantime  = 600
action   = iptables-multiport[name=nginx-ratelimit, port="http,https", protocol=tcp]
